### ISSUE TITLE
What's in car_22_backup.img?

### ISSUE THREAD

**Issue by jyl087** [mit-racecar/install_tools#3]
Hi, I have a TX2 board with JetPack 3.1 installed. I'm trying to follow the instructions here and wanted to know what was in the car_22_backup.img file, and whether the contents within could be manually installed on my TX2? I tried to mount the .img file as an ext4 partition but got an error.

**Comment by Winter-Guerra** [comment]
Resolved via email. However, the readme should be updated to use a jetpack
version instead.

**Comment by Taimoor-Shakeel** [comment]
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.82.6, 2620:100:6032:6::a27d:5206
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.82.6|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-27 08:04:46 ERROR 404: Not Found.

From where I can download this file because it is deleted from this link?

**Comment by Winter-Guerra** [comment]
Hi @Taimoor-Shakeel , sorry for the wait. If I recall correctly, the online documentation refers to [this image](https://www.dropbox.com/s/d1s02mbpmhtdpry/car_22_backup.img.tar.gz?dl=1). Dropbox recently changed their URL structure and broke the link.

Best,
-Winter
